# General
# name: test_run
name: 1_resnet50_gn_ws
root: data/interim
batch_size: 16
workers: 6
augmentation: medium
debug: False
opt_level: O1
resume: ""
fold: 0
pos_weight: 0.8

# Model
segm_arch: unet
backbone: resnet50
model_params: {
    encoder_weights: 'imagenet_gn_ws', 
    norm_layer: 'agn', 
    # norm_act: 'leaky_relu', 
    decoder_channels: [256, 128, 64, 32, 32]}
ws: True

# Training
optim: adamw
weight_decay: 0.00001
size: 512
phases: [{'ep':[0, 30], 'lr': [ 0.01 , 0.0001], 'mode': 'cos'}]
decoder_warmup_epochs: 0
criterion: [bce, 0.5, dice, 0.5]

# Validation&Testing
validate: False
val_size: 768
tta: False



