# General
name: 2.baseline_resnet34
root: data/interim
batch_size: 8
workers: 6
augmentation: medium
debug: False
opt_level: O1
resume: "logs/1.baseline_resnet34/model.chpn"
fold: 0
pos_weight: 0.4

# Model
segm_arch: unet
backbone: resnet34
model_params: {}
ws: False
# model_params: {encoder_weights: None, norm_layer: 'agn', norm_act: 'leaky_relu'}
# ws: True

# Training
optim: adamw
weight_decay: 0.00001
size: 768
phases: [{'ep':[0, 20], 'lr': [ 0.001 , 0.05], 'mode': 'cos'},
        {'ep':[21, 40], 'lr': [ 0.05 , 0.0001], 'mode': 'cos'}, 
        {'ep':[40, 50], 'lr': [ 0.0001 , 0.0005], 'mode': 'linear'}, 
        {'ep':[50, 60], 'lr': [ 0.0005 , 0.00001], 'mode': 'cos'}, 
        ]
decoder_warmup_epochs: 0
criterion: [bce, 2, dice, 1, focal, 2]

# Validation&Testing
validate: False
val_size: 768
tta: False



