batch_size: 32
workers: 16
augmentation: medium
debug: False
opt_level: O1
resume: ""

# Model
segm_arch: unet
backbone: resnet34

model_params: {
    encoder_weights: 'imagenet',
    norm_layer: 'inplaceabn',
    norm_act: 'leaky_relu',
    decoder_channels: [256, 128, 64, 32, 32]}

ws: False

# Training
use_jsrt_china_dataset: True
optim: adam
weight_decay: 0.00001
phases: [
    {'ep':[0, 10], 'lr': 0.001, pos_weight: 0.52, lung_weigth: 0.41, size: 512, val_size: 512},
    {'ep':[10, 20], 'lr': 0.0001, pos_weight: 0.46, lung_weigth: 0.44,  size: 512, val_size: 512},
    {'ep':[20, 30], 'lr': [0.0001, 0.00001], mode: 'cos', pos_weight: 0.66, lung_weigth: 0, size: 512, val_size: 512},
]

decoder_warmup_epochs: 1
criterion: [bce, 1]

# Validation&Testing
validate: False
val_size: 512
tta: False



