batch_size: 8
workers: 16
augmentation: light_medium
debug: False
opt_level: O1
resume: "baseline"

# Model
segm_arch: unet
backbone: resnet34

model_params: {
    encoder_weights: 'imagenet',
    norm_layer: 'inplaceabn',
    norm_act: 'leaky_relu',
    decoder_channels: [256, 128, 64, 32, 32]}

ws: False

# Training
optim: adam
weight_decay: 0.00001
phases: [
    {'ep':[0, 5], 'lr': 0.0001, pos_weight: 0.4, size: 1024, val_size: 1024},
    {'ep':[5, 10], 'lr': [0.0001, 0.00001], mode: 'cos', pos_weight: 0.4, size: 1024, val_size: 1024},
]
decoder_warmup_epochs: 0
criterion: [bce, 1]

# Validation&Testing
validate: False
val_size: 1024
tta: False



