# General
name: test_run
seed: 42
root: data/raw
batch_size: 8
workers: 6
augmentation: light
debug: False
opt_level: O0
resume: ""
fold: 0
pos_weight: 0.5

# Model
segm_arch: unet
backbone: resnet34
model_params: {}

# Training
optim: adamw
weight_decay: 0.00001
size: 512
phases: [{'ep':[0, 40], 'lr': [ 0.01 , 0.00001], 'mode': 'cos'}]
decoder_warmup_epochs: 10
criterion: [focal, 0.5, dice, 0.5]

# Validation&Testing
validate: False
val_size: 512
tta: False



