batch_size: 40
workers: 16
augmentation: medium
debug: False
opt_level: O1
resume: ""
pos_weight: 0.8

# Model
segm_arch: unet
backbone: resnet34

model_params: {
    encoder_weights: 'imagenet',
    norm_layer: 'inplaceabn',
    norm_act: 'leaky_relu',
    decoder_channels: [256, 128, 64, 32, 32]}

ws: True

# Training
optim: adam
weight_decay: 0.00001
size: 512
phases: [{'ep':[0, 60], 'lr': [ 0.01 , 0.0001], 'mode': 'cos'}]
decoder_warmup_epochs: 0
criterion: [bce, 1]

# Validation&Testing
validate: False
val_size: 512
tta: False



