batch_size: 40
workers: 16
augmentation: medium
debug: False
opt_level: O1
resume: ""
pos_weight: 0.8

# Model
segm_arch: linknet
backbone: resnet34

model_params: {
    encoder_weights: 'imagenet',
    norm_layer: 'inplaceabn',
    norm_act: 'leaky_relu',
#    decoder_channels: [256, 128, 64, 32, 32]
}

ws: False

# Training
optim: adam
weight_decay: 0.00001
size: 512
phases: [
    {'ep':[0, 10], 'lr': 0.001},
]
decoder_warmup_epochs: 1
criterion: [bce, 3, dice, 1]

# Validation&Testing
validate: False
val_size: 512
tta: False



