batch_size: 40
workers: 16
augmentation: medium
debug: False
opt_level: O1
resume: ""
pos_weight: 0.8

# Model
segm_arch: unet
backbone: resnet34

model_params: {
    encoder_weights: 'imagenet',
    norm_layer: 'inplaceabn',
    norm_act: 'leaky_relu',
    decoder_channels: [256, 128, 64, 32, 32]}

ws: False

# Training
optim: adam
weight_decay: 0.00001
size: 512
phases: [
    {'ep':[0, 30], 'lr': 0.001, mode: ReduceLROnPlateau,
        "params": {'factor':0.3, "patience":1, "min_lr":0.000001, "mode":"min", "restore_best_weights": True}},
    {'ep':[30, 40], 'lr': [0.0005, 0.00005], mode: 'cos'},
    {'ep':[40, 50], 'lr': [0.00005, 0.000005], mode: 'cos'},
]

early_stopping:
    min_delta: 0.00001
    patience: 3
    mode: "min"
    restore_best_weights: True

decoder_warmup_epochs: 1
criterion: [bce, 1]

# Validation&Testing
validate: False
val_size: 512
tta: False



